namespace Square.Html;

/// <summary>
/// AOT-friendly explicit factory for the 113 frozen HTML elements. Each tag maps to a static
/// construction delegate — no reflection, no activation — and must stay aligned with
/// <see cref="HtmlTagCatalog.TypeNames"/>; phase verification cross-checks the two tables plus
/// the concrete types so a missing or duplicated entry fails loudly.
/// </summary>
public static class HtmlElementFactory
{
    private static readonly Dictionary<string, Func<HTMLElement>> Factories = new(StringComparer.Ordinal)
    {
        ["a"] = static () => new HTMLAnchorElement(),
        ["abbr"] = static () => new HTMLAbbrElement(),
        ["address"] = static () => new HTMLAddressElement(),
        ["area"] = static () => new HTMLAreaElement(),
        ["article"] = static () => new HTMLArticleElement(),
        ["aside"] = static () => new HTMLAsideElement(),
        ["audio"] = static () => new HTMLAudioElement(),
        ["b"] = static () => new HTMLBElement(),
        ["base"] = static () => new HTMLBaseElement(),
        ["bdi"] = static () => new HTMLBdiElement(),
        ["bdo"] = static () => new HTMLBdoElement(),
        ["blockquote"] = static () => new HTMLBlockquoteElement(),
        ["body"] = static () => new HTMLBodyElement(),
        ["br"] = static () => new HTMLBRElement(),
        ["button"] = static () => new HTMLButtonElement(),
        ["canvas"] = static () => new HTMLCanvasElement(),
        ["caption"] = static () => new HTMLTableCaptionElement(),
        ["cite"] = static () => new HTMLCiteElement(),
        ["code"] = static () => new HTMLCodeElement(),
        ["col"] = static () => new HTMLColElement(),
        ["colgroup"] = static () => new HTMLColgroupElement(),
        ["data"] = static () => new HTMLDataElement(),
        ["datalist"] = static () => new HTMLDataListElement(),
        ["dd"] = static () => new HTMLDdElement(),
        ["del"] = static () => new HTMLDelElement(),
        ["details"] = static () => new HTMLDetailsElement(),
        ["dfn"] = static () => new HTMLDfnElement(),
        ["dialog"] = static () => new HTMLDialogElement(),
        ["div"] = static () => new HTMLDivElement(),
        ["dl"] = static () => new HTMLDListElement(),
        ["dt"] = static () => new HTMLDtElement(),
        ["em"] = static () => new HTMLEmElement(),
        ["embed"] = static () => new HTMLEmbedElement(),
        ["fieldset"] = static () => new HTMLFieldSetElement(),
        ["figcaption"] = static () => new HTMLFigcaptionElement(),
        ["figure"] = static () => new HTMLFigureElement(),
        ["footer"] = static () => new HTMLFooterElement(),
        ["form"] = static () => new HTMLFormElement(),
        ["h1"] = static () => new HTMLH1Element(),
        ["h2"] = static () => new HTMLH2Element(),
        ["h3"] = static () => new HTMLH3Element(),
        ["h4"] = static () => new HTMLH4Element(),
        ["h5"] = static () => new HTMLH5Element(),
        ["h6"] = static () => new HTMLH6Element(),
        ["head"] = static () => new HTMLHeadElement(),
        ["header"] = static () => new HTMLHeaderElement(),
        ["hgroup"] = static () => new HTMLHgroupElement(),
        ["hr"] = static () => new HTMLHRElement(),
        ["html"] = static () => new HTMLHtmlElement(),
        ["i"] = static () => new HTMLIElement(),
        ["iframe"] = static () => new HTMLIFrameElement(),
        ["img"] = static () => new HTMLImageElement(),
        ["input"] = static () => new HTMLInputElement(),
        ["ins"] = static () => new HTMLInsElement(),
        ["kbd"] = static () => new HTMLKbdElement(),
        ["label"] = static () => new HTMLLabelElement(),
        ["legend"] = static () => new HTMLLegendElement(),
        ["li"] = static () => new HTMLLIElement(),
        ["link"] = static () => new HTMLLinkElement(),
        ["main"] = static () => new HTMLMainElement(),
        ["map"] = static () => new HTMLMapElement(),
        ["mark"] = static () => new HTMLMarkElement(),
        ["menu"] = static () => new HTMLMenuElement(),
        ["meta"] = static () => new HTMLMetaElement(),
        ["meter"] = static () => new HTMLMeterElement(),
        ["nav"] = static () => new HTMLNavElement(),
        ["noscript"] = static () => new HTMLNoscriptElement(),
        ["object"] = static () => new HTMLObjectElement(),
        ["ol"] = static () => new HTMLOListElement(),
        ["optgroup"] = static () => new HTMLOptGroupElement(),
        ["option"] = static () => new HTMLOptionElement(),
        ["output"] = static () => new HTMLOutputElement(),
        ["p"] = static () => new HTMLParagraphElement(),
        ["picture"] = static () => new HTMLPictureElement(),
        ["pre"] = static () => new HTMLPreElement(),
        ["progress"] = static () => new HTMLProgressElement(),
        ["q"] = static () => new HTMLQElement(),
        ["rp"] = static () => new HTMLRpElement(),
        ["rt"] = static () => new HTMLRtElement(),
        ["ruby"] = static () => new HTMLRubyElement(),
        ["s"] = static () => new HTMLSElement(),
        ["samp"] = static () => new HTMLSampElement(),
        ["script"] = static () => new HTMLScriptElement(),
        ["search"] = static () => new HTMLSearchElement(),
        ["section"] = static () => new HTMLSectionElement(),
        ["select"] = static () => new HTMLSelectElement(),
        ["selectedcontent"] = static () => new HTMLSelectedContentElement(),
        ["slot"] = static () => new HTMLSlotElement(),
        ["small"] = static () => new HTMLSmallElement(),
        ["source"] = static () => new HTMLSourceElement(),
        ["span"] = static () => new HTMLSpanElement(),
        ["strong"] = static () => new HTMLStrongElement(),
        ["style"] = static () => new HTMLStyleElement(),
        ["sub"] = static () => new HTMLSubElement(),
        ["summary"] = static () => new HTMLSummaryElement(),
        ["sup"] = static () => new HTMLSupElement(),
        ["table"] = static () => new HTMLTableElement(),
        ["tbody"] = static () => new HTMLTbodyElement(),
        ["td"] = static () => new HTMLTdElement(),
        ["template"] = static () => new HTMLTemplateElement(),
        ["textarea"] = static () => new HTMLTextAreaElement(),
        ["tfoot"] = static () => new HTMLTfootElement(),
        ["th"] = static () => new HTMLThElement(),
        ["thead"] = static () => new HTMLTheadElement(),
        ["time"] = static () => new HTMLTimeElement(),
        ["title"] = static () => new HTMLTitleElement(),
        ["tr"] = static () => new HTMLTableRowElement(),
        ["track"] = static () => new HTMLTrackElement(),
        ["u"] = static () => new HTMLUElement(),
        ["ul"] = static () => new HTMLUListElement(),
        ["var"] = static () => new HTMLVarElement(),
        ["video"] = static () => new HTMLVideoElement(),
        ["wbr"] = static () => new HTMLWbrElement(),
    };
    internal static IReadOnlyDictionary<string, Func<HTMLElement>> Registrations => Factories;


    /// <summary>Creates the concrete element for a catalog tag (normalized to lowercase like the old host).</summary>
    public static HTMLElement Create(string tag)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);
        if (Factories.TryGetValue(Square.UI.ElementRegistry.Normalize(Square.UI.ElementRegistry.HtmlNamespaceUri, tag), out var factory)) return factory();
        throw new ArgumentException($"Unknown HTML element '{tag}'.", nameof(tag));
    }
}
