<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(IsWindowsBuild)' != 'false'">WinExe</OutputType>
    <OutputType Condition="'$(IsWindowsBuild)' == 'false'">Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Description>Square Sample Application</Description>
    <IsPackable>false</IsPackable>
    <PublishAot Condition="'$(SquareSamplePublishAot)' == 'true'">true</PublishAot>
    <SquareSampleUseVulkan Condition="'$(SquareSampleUseVulkan)' == '' and '$(SquareSamplePublishAot)' != 'true'">true</SquareSampleUseVulkan>
    <SquareSampleUseVulkan Condition="'$(SquareSampleUseVulkan)' == ''">false</SquareSampleUseVulkan>
    <SquareSampleUseSkia Condition="'$(SquareSampleUseSkia)' == '' and '$(SquareSamplePublishAot)' != 'true'">true</SquareSampleUseSkia>
    <SquareSampleUseSkia Condition="'$(SquareSampleUseSkia)' == ''">false</SquareSampleUseSkia>
    <SquareSampleUseDirect2D Condition="'$(SquareSampleUseDirect2D)' == '' and '$(SquareTargetPlatform)' == 'Win32' and '$(SquareSamplePublishAot)' != 'true'">true</SquareSampleUseDirect2D>
    <SquareSampleUseDirect2D Condition="'$(SquareSampleUseDirect2D)' == ''">false</SquareSampleUseDirect2D>
    <SquareSampleUseDevTools Condition="'$(SquareSampleUseDevTools)' == '' and '$(SquareSamplePublishAot)' != 'true'">true</SquareSampleUseDevTools>
    <SquareSampleUseDevTools Condition="'$(SquareSampleUseDevTools)' == ''">false</SquareSampleUseDevTools>
    <EmitCompilerGeneratedFiles Condition="'$(SquareEmitCompilerGeneratedFiles)' == 'true'">true</EmitCompilerGeneratedFiles>
    <OptimizationPreference>Size</OptimizationPreference>
    <DefineConstants Condition="'$(SquareSampleUseVulkan)' == 'true'">$(DefineConstants);SQUARE_SAMPLE_VULKAN</DefineConstants>
    <DefineConstants Condition="'$(SquareSampleUseSkia)' == 'true'">$(DefineConstants);SQUARE_SAMPLE_SKIA</DefineConstants>
    <DefineConstants Condition="'$(SquareSampleUseDirect2D)' == 'true' and '$(SquareTargetPlatform)' == 'Win32'">$(DefineConstants);SQUARE_SAMPLE_DIRECT2D</DefineConstants>
    <DefineConstants Condition="'$(SquareSampleUseDevTools)' == 'true'">$(DefineConstants);SQUARE_SAMPLE_DEVTOOLS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Square\Square.csproj" />
    <ProjectReference Include="..\..\src\Square.Extensions\Square.Extensions.csproj" />
    <ProjectReference Include="..\..\src\Square.Platform.Win32\Square.Platform.Win32.csproj" Condition="'$(SquareTargetPlatform)' == 'Win32'" />
    <ProjectReference Include="..\..\src\Square.Platform.X11\Square.Platform.X11.csproj" Condition="'$(SquareTargetPlatform)' == 'X11'" />
    <ProjectReference Include="..\..\src\Square.Platform.MacOS\Square.Platform.MacOS.csproj" Condition="'$(SquareTargetPlatform)' == 'MacOS'" />
    <ProjectReference Include="..\..\src\Square.Backends.Vulkan\Square.Backends.Vulkan.csproj" Condition="'$(SquareSampleUseVulkan)' == 'true'" />
    <ProjectReference Include="..\..\src\Square.Backends.Skia\Square.Backends.Skia.csproj" Condition="'$(SquareSampleUseSkia)' == 'true'" />
    <ProjectReference Include="..\..\src\Square.Backends.Direct2D\Square.Backends.Direct2D.csproj" Condition="'$(SquareSampleUseDirect2D)' == 'true' and '$(SquareTargetPlatform)' == 'Win32'" />
    <ProjectReference Include="..\..\src\Square.DevTools\Square.DevTools.csproj" Condition="'$(SquareSampleUseDevTools)' == 'true'" />
    <ProjectReference Include="..\..\src\Square.Compiler\Square.Compiler.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="**\*.sqx" />
    <Compile Include="..\..\src\Square.Platform.Win32\buildTransitive\Square.Platform.Win32.Registration.cs" Link="Square.Generated\PlatformRegistration.g.cs" Condition="'$(SquareTargetPlatform)' == 'Win32'" />
    <Compile Include="..\..\src\Square.Platform.X11\buildTransitive\Square.Platform.X11.Registration.cs" Link="Square.Generated\PlatformRegistration.g.cs" Condition="'$(SquareTargetPlatform)' == 'X11'" />
    <Compile Include="..\..\src\Square.Platform.MacOS\buildTransitive\Square.Platform.MacOS.Registration.cs" Link="Square.Generated\PlatformRegistration.g.cs" Condition="'$(SquareTargetPlatform)' == 'MacOS'" />
  </ItemGroup>

</Project>
