<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Square.Sample.WebServer</RootNamespace>
    <IsPackable>false</IsPackable>
    <Description>Square static semantic HTML Web Server sample</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Square.Hosting.Web\Square.Hosting.Web.csproj" />
    <ProjectReference Include="..\..\src\Square.Compiler\Square.Compiler.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="**\*.sqv" />
  </ItemGroup>

</Project>
