<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="PublishAot">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <Description>Square markup compiler and Roslyn source generator</Description>
    <LangVersion>latest</LangVersion>
    <PublishAot>false</PublishAot>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <IncludeSymbols>false</IncludeSymbols>
    <PackageTags>$(PackageTags);source-generator;roslyn;sqx;sqv</PackageTags>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackSquareCompilerAnalyzer</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);RS1035;RS2008</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <Nullable>annotations</Nullable>
    <NoWarn>$(NoWarn);RS1035;RS2008;RS1041;RS1036</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Square.SourceGenerator.Tests" />
    <InternalsVisibleTo Include="Square.LanguageServer" />
    <InternalsVisibleTo Include="Square.LanguageServer.Tests" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <Compile Remove="Markup\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="buildTransitive\Square.Compiler.props" Pack="true" PackagePath="buildTransitive\$(PackageId).props" Visible="false" />
    <None Include="buildTransitive\Square.Compiler.targets" Pack="true" PackagePath="buildTransitive\$(PackageId).targets" Visible="false" />
  </ItemGroup>

  <Target Name="PackSquareCompilerAnalyzer" Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(TargetPath)" PackagePath="analyzers/dotnet/cs" />
    </ItemGroup>
  </Target>

</Project>
