using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Square.Compiler.Directives;
using Square.Compiler.Emit;
using Square.Compiler.LanguageServices;
using Square.Compiler.Parser;
using Square.Compiler.Template.Ir;

namespace Square.Compiler;

[Generator]
public sealed class SqxGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var inputs = context.AdditionalTextsProvider
            .Where(file => TemplateNamespaceResolver.IsTemplateFile(file.Path))
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select((pair, cancellationToken) =>
            {
                var file = pair.Left;
                var options = pair.Right;
                options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);
                options.GlobalOptions.TryGetValue("build_property.MSBuildProjectDirectory", out var projectDirectory);
                options.GetOptions(file).TryGetValue("build_metadata.AdditionalFiles.Link", out var logicalPath);
                return new SqxInput(
                    file.Path,
                    file.GetText(cancellationToken)?.ToString() ?? "",
                    TemplateNamespaceResolver.GetDefaultNamespace(
                        rootNamespace ?? "Square.Sample",
                        file.Path,
                        projectDirectory,
                        logicalPath));
            })
            .Collect();

        context.RegisterSourceOutput(inputs, static (productionContext, files) =>
        {
            if (files.Length == 0) return;
            productionContext.AddSource("SquareHotReload.g.cs", SourceText.From(
                """
                // <auto-generated/>
                #if DEBUG
                [assembly: System.Reflection.Metadata.MetadataUpdateHandler(typeof(Square.Hosting.SquareHotReloadHandler))]
                #endif
                """, Encoding.UTF8));
        });

        // Compilation drives directive catalog refresh (metadata scan of referenced assemblies).
        var compilationAndInputs = context.CompilationProvider.Combine(inputs);

        context.RegisterSourceOutput(compilationAndInputs, static (productionContext, pair) =>
        {
            var compilation = pair.Left;
            var files = pair.Right;
            var semanticAnalyzer = new TemplateSemanticAnalyzer();
            var semanticInputs = files.Select(file => (file.Path, file.Content, file.Namespace)).ToArray();
            var analysis = semanticAnalyzer.AnalyzeProject(compilation, semanticInputs, productionContext.CancellationToken);
            var sourceTexts = files.ToDictionary(file => file.Path, file => file.Content, StringComparer.Ordinal);
            foreach (var diagnostic in analysis.Diagnostics)
                ReportCatalogDiagnostics(productionContext, compilation, new[] { diagnostic }, sourceTexts);
            foreach (var source in analysis.GeneratedSources)
                productionContext.AddSource(source.Key, SourceText.From(source.Value, Encoding.UTF8));
        });
    }

    private static void ReportCatalogDiagnostics(
        SourceProductionContext context,
        Compilation compilation,
        IReadOnlyList<SquareDiagnostic> diagnostics,
        IReadOnlyDictionary<string, string> sourceTexts = null)
    {
        foreach (var diagnostic in diagnostics)
        {
            var location = Location.None;
            if (!string.IsNullOrWhiteSpace(diagnostic.SourcePath))
            {
                var tree = compilation.SyntaxTrees.FirstOrDefault(candidate =>
                    string.Equals(candidate.FilePath, diagnostic.SourcePath, StringComparison.OrdinalIgnoreCase));
                if (tree != null)
                {
                    var source = tree.GetText();
                    var span = diagnostic.Range.ToTextSpan(source);
                    location = Location.Create(tree, span);
                }
                else if (sourceTexts != null && sourceTexts.TryGetValue(diagnostic.SourcePath, out var text))
                {
                    var source = SourceText.From(text, Encoding.UTF8);
                    var span = diagnostic.Range.ToTextSpan(source);
                    location = Location.Create(diagnostic.SourcePath, span, source.Lines.GetLinePositionSpan(span));
                }
            }
            var descriptor = diagnostic.Id.StartsWith("SQXE", StringComparison.Ordinal)
                ? Diagnostics.ElementDiagnostics.Get(diagnostic.Id)
                : diagnostic.Id.StartsWith("SQV", StringComparison.Ordinal)
                    ? Diagnostics.SqvDiagnostics.Get(diagnostic.Id)
                    : new Microsoft.CodeAnalysis.DiagnosticDescriptor(
                        diagnostic.Id, diagnostic.Message, "{0}", "Square.Elements", Microsoft.CodeAnalysis.DiagnosticSeverity.Error, true);
            context.ReportDiagnostic(Diagnostic.Create(
                descriptor,
                location,
                diagnostic.Message));
        }
    }

    private static uint StableHash(string value)
    {
        unchecked
        {
            var hash = 2166136261u;
            foreach (var character in value)
                hash = (hash ^ character) * 16777619u;
            return hash;
        }
    }

    private sealed class SqxInput
    {
        public string Path { get; }
        public string Content { get; }
        public string Namespace { get; }

        public SqxInput(string path, string content, string namespaceName)
        {
            Path = path;
            Content = content;
            Namespace = namespaceName;
        }
    }

}
