<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Square.VisualStudio</RootNamespace>
    <AssemblyName>Square.VisualStudio</AssemblyName>
    <MinimumVisualStudioVersion>17.0</MinimumVisualStudioVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>
    <OutDir>$(OutputPath)</OutDir>
    <TargetVsixContainerName>Square.LanguageSupport.VisualStudio.vsix</TargetVsixContainerName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePkgDefFile>false</GeneratePkgDefFile>
    <CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>false</CopyOutputSymbolsToOutputDirectory>
    <IncludeAssemblyInVSIXContainer>false</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="source.extension.vsixmanifest">
      <IncludeInVSIX>true</IncludeInVSIX>
    </None>
    <Content Include="Square.pkgdef">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="..\square-language\syntaxes\sqx.tmLanguage.json">
      <Link>Grammars\sqx.tmLanguage.json</Link>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="..\square-language\syntaxes\sqv.tmLanguage.json">
      <Link>Grammars\sqv.tmLanguage.json</Link>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="..\square-language\language-configuration.json">
      <Link>language-configuration.json</Link>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="..\vscode-square\LICENSE.txt">
      <Link>LICENSE.txt</Link>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
  </ItemGroup>

  <Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets"
          Condition="Exists('$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets')" />

  <Target Name="BuildVsixContainer"
          AfterTargets="Build"
          DependsOnTargets="CreateVsixContainer" />

</Project>
