<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>Square desktop UI framework</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StbTrueTypeSharp" />
    <PackageReference Include="Yoga.Net" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Square.Backends.Tests" />
    <InternalsVisibleTo Include="Square.CSS.Tests" />
    <InternalsVisibleTo Include="Square.Images.Tests" />
    <InternalsVisibleTo Include="Square.Platform.Win32" />
    <InternalsVisibleTo Include="Square.Platform.X11" />
    <InternalsVisibleTo Include="Square.Platform.MacOS" />
    <InternalsVisibleTo Include="Square.UI.Tests" />
    <InternalsVisibleTo Include="Square.DevTools.Tests" />
    <InternalsVisibleTo Include="Square.Backends.Skia" />
    <InternalsVisibleTo Include="Square.Backends.Direct2D" />
    <InternalsVisibleTo Include="Square.Extensions.CodeEditor" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
  </ItemGroup>

</Project>
