using System.Text;
using Square.Compiler.Directives;
using Square.Compiler.Parser;
using Square.Compiler.Template;

namespace Square.Compiler.Emit
{
    internal sealed class ComponentEmitter
    {
        private readonly TemplateDocument _doc;
        private readonly string _namespace;
        private readonly StringBuilder _sb = new StringBuilder();
        private readonly List<RefInfo> _refs = new List<RefInfo>();
        private readonly DirectiveCatalog _catalog;
        private DirectiveEmitPipeline _pipeline;
        private readonly Dictionary<string, int> _structCounts = new Dictionary<string, int>(StringComparer.Ordinal);
        private int _vforIndex;
        private int _vifIndex;
        private int _varCounter;
        private int _slotCounter;
        private bool _hasObjectBindings;

        public ComponentEmitter(SqxDocument doc, string namespaceName = "Square.Sample", DirectiveCatalog catalog = null)
            : this(TemplateDocument.From(doc), namespaceName, catalog)
        {
        }

        public ComponentEmitter(TemplateDocument doc, string namespaceName = "Square.Sample", DirectiveCatalog catalog = null)
        {
            _doc = doc;
            _catalog = catalog ?? DirectiveCatalog.BuiltIn;
            _namespace = !string.IsNullOrWhiteSpace(doc.Namespace)
                ? doc.Namespace
                : string.IsNullOrWhiteSpace(namespaceName) ? "Square.Sample" : namespaceName;
        }

        public string Emit()
        {
            ResetState();
            CollectRefs(_doc.Roots);
            CountStructs(_doc.Roots);
            _hasObjectBindings = HasObjectBindings(_doc.Roots);
            var (scriptUsings, scriptBody) = SplitScriptUsings(_doc.ScriptCode);

            _sb.AppendLine("// <auto-generated/>");
            _sb.AppendLine("#nullable enable");
            _sb.AppendLine();
            _sb.AppendLine("using Square.UI;");
            _sb.AppendLine("using Square.Events;");
            _sb.AppendLine("using Square.Runtime;");
            _sb.AppendLine("using Square.Runtime.Binding;");
            _sb.AppendLine("using Square.Graphics;");
            _sb.AppendLine("using Square.Controls;");
            _sb.AppendLine("using Square.Controls.Primitives;");
            foreach (var usingDirective in scriptUsings)
                _sb.AppendLine(usingDirective);
            _sb.AppendLine();
            _sb.AppendLine("namespace " + _namespace + ";");
            _sb.AppendLine();
            _sb.AppendLine(_doc.Access + " partial class " + _doc.Name + " : UIElement");
            _sb.AppendLine("{");

            EmitFields();
            _sb.AppendLine("    public override void BuildElementTree()");
            _sb.AppendLine("    {");
            _sb.AppendLine("        if (_visualTreeBuilt) return;");
            _sb.AppendLine("        _visualTreeBuilt = true;");
            EmitNodes(_doc.Roots, "        ", "this", Array.Empty<string>());
            if (!string.IsNullOrWhiteSpace(_doc.StyleCode))
                _sb.AppendLine("        ApplyComponentStyles(this);");
            _sb.AppendLine("    }");

            EmitScript(scriptBody);
            EmitStyleSupport();
            _sb.AppendLine("}");
            return _sb.ToString();
        }

        private void ResetState()
        {
            _varCounter = 0;
            _slotCounter = 0;
            _hasObjectBindings = false;
            _vforIndex = 0;
            _vifIndex = 0;
            _structCounts.Clear();
            _refs.Clear();
            _sb.Clear();
            _pipeline = new DirectiveEmitPipeline(
                _sb,
                _catalog,
                EmitNodes,
                EmitFactoryBody,
                EmitAttribute,
                NextVariable);
            _pipeline.ResetFieldIndexes();
        }

        private void CollectRefs(List<SqxNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is SqxElement element)
                {
                    var refAttr = FindAttr(element, "ref");
                    if (refAttr != null && !string.IsNullOrWhiteSpace(refAttr.RawValue) &&
                        !_refs.Exists(item => item.Name == refAttr.RawValue))
                    {
                        _refs.Add(new RefInfo(refAttr.RawValue, MapTagName(element.TagName)));
                    }
                    CollectRefs(element.Children);
                }
                else if (node is TemplateForDirective forDirective)
                    CollectRefs(forDirective.Children);
                else if (node is TemplateIfChainDirective ifChain)
                    foreach (var branch in ifChain.Branches)
                        CollectRefs(branch.Children);
            }
        }

        private void CountStructs(List<SqxNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is SqxElement element)
                {
                    if (_catalog.TryGet(element.TagName, out var descriptor) &&
                        !descriptor.SkipStandaloneEmit &&
                        descriptor.Pattern == "ControlFlowAttach")
                    {
                        var prefix = string.IsNullOrEmpty(descriptor.FieldPrefix) ? "_dir" : descriptor.FieldPrefix;
                        if (!_structCounts.TryGetValue(prefix, out var count)) count = 0;
                        _structCounts[prefix] = count + 1;
                    }
                    CountStructs(element.Children);
                }
                else if (node is TemplateForDirective)
                {
                    _structCounts["_vfor"] = (_structCounts.TryGetValue("_vfor", out var c) ? c : 0) + 1;
                    CountStructs(((TemplateForDirective)node).Children);
                }
                else if (node is TemplateIfChainDirective ifChain)
                {
                    _structCounts["_vif"] = (_structCounts.TryGetValue("_vif", out var c2) ? c2 : 0) + ifChain.Branches.Count;
                    foreach (var branch in ifChain.Branches)
                        CountStructs(branch.Children);
                }
            }
        }

        private void EmitFields()
        {
            _sb.AppendLine("    private bool _visualTreeBuilt;");
            foreach (var item in _refs)
                _sb.AppendLine("    internal " + item.TypeName + " " + item.Name + " = null!;");

            foreach (var descriptor in _catalog.Descriptors
                         .Where(descriptor => descriptor.Pattern == "ControlFlowAttach" &&
                             !string.IsNullOrWhiteSpace(descriptor.FieldPrefix) &&
                             !string.IsNullOrWhiteSpace(descriptor.RuntimeTypeName))
                         .GroupBy(descriptor => descriptor.FieldPrefix, StringComparer.Ordinal)
                         .Select(group => group.First()))
                EmitStructFields(descriptor.FieldPrefix, GetDirectiveFieldType(descriptor));
            // Vue 专属结构节点
            EmitStructFields("_vfor", "IForNode");
            EmitStructFields("_vif", "ShowNode");
            _sb.AppendLine();
        }

        private void EmitStructFields(string prefix, string typeName)
        {
            var count = _structCounts.TryGetValue(prefix, out var c) ? c : 0;
            for (var i = 0; i < count; i++)
                _sb.AppendLine("    private " + typeName + " " + prefix + i + " = null!;");
        }

        private static string GetDirectiveFieldType(DirectiveDescriptor descriptor) =>
            descriptor.TagName is "For" or "Index" ? "IForNode" : descriptor.RuntimeTypeName;

        private void EmitDisposeFields(string prefix)
        {
            var count = _structCounts.TryGetValue(prefix, out var c) ? c : 0;
            for (var i = 0; i < count; i++)
                _sb.AppendLine("        " + prefix + i + "?.Dispose();");
        }

        private void EmitNullFields(string prefix)
        {
            var count = _structCounts.TryGetValue(prefix, out var c) ? c : 0;
            for (var i = 0; i < count; i++)
                _sb.AppendLine("        " + prefix + i + " = null!;");
        }

        private void EmitNodes(List<SqxNode> nodes, string indent, string parentName, IReadOnlyList<string> localNames)
        {
            foreach (var node in nodes)
            {
                if (IsWrapperExpression(node)) continue;

                if (node is SqxText text)
                {
                    if (string.IsNullOrWhiteSpace(text.Text)) continue;
                    var textName = EmitText(text.Text, indent);
                    _sb.AppendLine(indent + parentName + ".Children.Add(" + textName + ");");
                }
                else if (node is SqxExpression expression)
                {
                    var textName = EmitExpressionText(expression.Expression, indent, localNames);
                    _sb.AppendLine(indent + parentName + ".Children.Add(" + textName + ");");
                }
                else if (node is SqxElement element)
                {
                    if (IsTemplateFragment(element))
                    {
                        EmitNodes(element.Children, indent, parentName, localNames);
                        continue;
                    }

                    // Catalog-driven structural directives (Show/For/Switch/Slot/Router/…)
                    if (_catalog.IsDirective(element.TagName))
                    {
                        _pipeline.TryEmit(element, indent, parentName, localNames);
                        continue;
                    }

                    var elementName = EmitControl(element, indent, localNames, parentName);
                    _sb.AppendLine(indent + parentName + ".Children.Add(" + elementName + ");");
                    if (RequiresBuildAfterAttach(element.TagName))
                        _sb.AppendLine(indent + elementName + ".BuildElementTree();");
                }
                else if (node is TemplateForDirective forDirective)
                {
                    EmitVFor(forDirective, indent, parentName, localNames);
                }
                else if (node is TemplateIfChainDirective ifChain)
                {
                    EmitVIfChain(ifChain, indent, parentName, localNames);
                }
            }
        }

        private string EmitControl(SqxElement element, string indent, IReadOnlyList<string> localNames, string parentName = null)
        {
            var refAttr = FindAttr(element, "ref");
            var isRef = refAttr != null && !string.IsNullOrWhiteSpace(refAttr.RawValue);
            var variableName = isRef ? refAttr.RawValue : NextVariable();
            var tagName = MapTagName(element.TagName);
            var isCustomComponent = !IsBuiltInTag(element.TagName);
            var usesSlots = isCustomComponent || IsTitleBar(element.TagName);

            if (isRef)
                _sb.AppendLine(indent + variableName + " = new " + tagName + "();");
            else
                _sb.AppendLine(indent + "var " + variableName + " = new " + tagName + "();");
            _sb.AppendLine(indent + variableName + ".SetDebugInfo(ElementDebugInfo.Create(" +
                StableSourceId(_doc.SourcePath) + ", " + element.Line + ", " + element.Column + ", " +
                element.Line + ", " + (element.Column + Math.Max(1, element.TagName.Length)) +
                ", \"" + Escape(element.TagName) + "\", \"" + Escape(_doc.Name) + "\", sourcePath: \"" +
                Escape(_doc.SourcePath) + "\"));");

            foreach (var attribute in element.Attributes)
                EmitAttribute(variableName, attribute, indent, localNames);

            if (usesSlots)
            {
                EmitComponentSlots(element, variableName, indent, localNames);
            }
            else if (!EmitTextContent(element, variableName, indent, localNames))
                EmitNodes(element.Children, indent, variableName, localNames);

            return variableName;
        }

        private void EmitAttribute(string variableName, SqxAttribute attribute, string indent, IReadOnlyList<string> localNames)
        {
            if (attribute.Name == "ref" || attribute.Name == "slot") return;

            if (attribute.IsDynamicProperty)
            {
                _sb.AppendLine(indent + variableName + ".RegisterGeneratedResource(SqvObjectBinding.BindProperty(" + variableName + ", " + attribute.ArgumentExpression + ", " + attribute.RawValue + "));");
                return;
            }

            if (attribute.IsDynamicEvent)
            {
                _sb.AppendLine(indent + variableName + ".RegisterGeneratedResource(SqvObjectBinding.BindEvent(" + variableName + ", " + attribute.ArgumentExpression + ", " + attribute.RawValue + "));");
                return;
            }

            if (attribute.Name == "__sqv_bind_object")
            {
                _sb.AppendLine(indent + variableName + ".RegisterGeneratedResource(SqvObjectBinding.BindProperties(" + variableName + ", " + attribute.RawValue + "));");
                return;
            }

            if (attribute.Name == "__sqv_on_object")
            {
                _sb.AppendLine(indent + variableName + ".RegisterGeneratedResource(SqvObjectBinding.BindEvents(" + variableName + ", " + attribute.RawValue + "));");
                return;
            }

            if (attribute.Name == "class" && !attribute.IsExpression)
            {
                foreach (var className in Split(attribute.RawValue, ' '))
                    if (!string.IsNullOrWhiteSpace(className))
                        _sb.AppendLine(indent + variableName + ".ClassList.Add(\"" + Escape(className) + "\");");
                return;
            }

            if (attribute.Name == "style" && !attribute.IsExpression)
            {
                _sb.AppendLine(indent + variableName + ".Style.CssText = \"" + Escape(attribute.RawValue) + "\";");
                return;
            }

            if (attribute.IsExpression)
            {
                if (attribute.Name.StartsWith("on", StringComparison.OrdinalIgnoreCase))
                {
                    var eventName = attribute.Name.Substring(2).ToLowerInvariant();
                    EmitSourceMappedLine(indent, attribute.Line,
                        variableName + ".AddEventListener(\"" + eventName + "\", " + attribute.RawValue + ");");
                }
                else
                {
                    var propertyName = MapPropName(attribute.Name);
                    if (IsLocalExpression(attribute.RawValue, localNames))
                        EmitSourceMappedLine(indent, attribute.Line,
                            variableName + ".SetProperty(\"" + propertyName + "\", " + attribute.RawValue + ");");
                    else
                        EmitSourceMappedLine(indent, attribute.Line,
                            variableName + ".BindProperty(\"" + propertyName + "\", " + attribute.RawValue + ");");
                }
                return;
            }

            var propName = MapPropName(attribute.Name);
            var rawValue = attribute.RawValue ?? "";
            if (attribute.Name.Equals("disabled", StringComparison.OrdinalIgnoreCase) && string.IsNullOrEmpty(rawValue))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", true);");
            else if (bool.TryParse(rawValue, out var boolValue))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", " + boolValue.ToString().ToLowerInvariant() + ");");
            else if (int.TryParse(rawValue, out var intValue))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", " + intValue + ");");
            else
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", \"" + Escape(rawValue) + "\");");
        }

        private bool EmitTextContent(SqxElement element, string variableName, string indent, IReadOnlyList<string> localNames)
        {
            if (!IsTextContentElement(element.TagName)) return false;
            if (FindAttr(element, "text") != null) return true;

            var content = element.Children.Where(node => !IsWrapperExpression(node)).ToList();
            if (content.Count == 0) return true;
            if (content.All(node => node is SqxText))
            {
                var value = string.Concat(content.Cast<SqxText>().Select(node => node.Text));
                _sb.AppendLine(indent + variableName + ".SetProperty(\"TextContent\", \"" + Escape(NormalizeText(value)) + "\");");
                return true;
            }
            if (content.Count == 1 && content[0] is SqxExpression expression)
            {
                if (IsLocalExpression(expression.Expression, localNames))
                    _sb.AppendLine(indent + variableName + ".SetProperty(\"TextContent\", (" + expression.Expression + ")?.ToString() ?? \"\");");
                else
                    _sb.AppendLine(indent + variableName + ".BindProperty(\"TextContent\", " + expression.Expression + ");");
                return true;
            }
            if (content.All(node => node is SqxText or SqxExpression))
            {
                var parts = content.Select(node => node switch
                {
                    SqxText text => "\"" + Escape(text.Text) + "\"",
                    SqxExpression expression => "((" + expression.Expression + ")?.ToString() ?? \"\")",
                    _ => "\"\""
                });
                var sources = content.OfType<SqxExpression>()
                    .Select(expression => expression.Expression.Trim())
                    .Where(IsSimpleMemberExpression)
                    .Distinct(StringComparer.Ordinal)
                    .ToList();
                var sourceArgs = sources.Count == 0 ? "" : ", " + string.Join(", ", sources);
                _sb.AppendLine(indent + variableName + ".BindProperty(\"TextContent\", () => " +
                    string.Join(" + ", parts) + sourceArgs + ");");
                return true;
            }
            return false;
        }

        private void EmitComponentSlots(SqxElement element, string variableName, string indent, IReadOnlyList<string> localNames)
        {
            var groups = new List<SlotGroup>();
            foreach (var child in element.Children)
            {
                if (IsWrapperExpression(child)) continue;
                var slotName = "";
                var slotNameIsExpression = false;
                TemplateSlotScope slotScope = null;
                var slotNodes = new List<SqxNode> { child };
                if (child is SqxElement childElement)
                {
                    var slotAttribute = FindAttr(childElement, "slot");
                    slotName = slotAttribute?.RawValue ?? "";
                    slotNameIsExpression = slotAttribute?.IsExpression == true;
                    slotScope = childElement.SlotScope;
                    if (IsTemplateFragment(childElement))
                        slotNodes = childElement.Children;
                }

                var groupIndex = groups.FindIndex(group =>
                    group.NameIsExpression == slotNameIsExpression &&
                    string.Equals(group.Name, slotName, StringComparison.Ordinal) &&
                    ReferenceEquals(group.Scope, slotScope));
                if (groupIndex < 0)
                {
                    groups.Add(new SlotGroup(slotName, slotNameIsExpression, slotScope, new List<SqxNode>(slotNodes)));
                }
                else
                {
                    groups[groupIndex].Nodes.AddRange(slotNodes);
                }
            }

            foreach (var group in groups)
            {
                var parentParameter = "__slotParent" + _slotCounter++;
                var name = group.NameIsExpression ? group.Name : "\"" + Escape(group.Name) + "\"";
                var parameters = group.Scope == null
                    ? parentParameter
                    : "(" + parentParameter + ", __slotProps)";
                _sb.AppendLine(indent + variableName + ".Slots.Set(" + name + ", " + parameters + " =>");
                _sb.AppendLine(indent + "{");
                var scopeLocals = localNames;
                if (!string.IsNullOrWhiteSpace(group.Scope?.WholePropsName))
                {
                    _sb.AppendLine(indent + "    var " + group.Scope.WholePropsName + " = __slotProps;");
                    scopeLocals = AddLocals(scopeLocals, group.Scope.WholePropsName);
                }
                else if (group.Scope != null)
                {
                    foreach (var binding in group.Scope.Properties)
                    {
                        _sb.AppendLine(indent + "    var " + binding.LocalName + " = __slotProps.Get<" + binding.TypeName + ">(\"" + Escape(binding.PropertyName) + "\");");
                        scopeLocals = AddLocals(scopeLocals, binding.LocalName);
                    }
                }
                EmitNodes(group.Nodes, indent + "    ", parentParameter, scopeLocals);
                _sb.AppendLine(indent + "});");
            }
        }

        private void EmitVFor(TemplateForDirective directive, string indent, string parentName, IReadOnlyList<string> localNames)
        {
            var field = "_vfor" + _vforIndex++;
            var item = directive.ItemName;
            var hasIndex = !string.IsNullOrEmpty(directive.IndexName);
            var lambda = hasIndex ? "(" + item + ", " + directive.IndexName + ")" : item;
            var keySelector = string.IsNullOrWhiteSpace(directive.KeyExpression)
                ? ""
                : lambda + " => " + directive.KeyExpression + ", ";
            _sb.AppendLine(indent + field + " = ForNode.Create(" + directive.SourceExpression + ", " + keySelector + lambda + " =>");
            _sb.AppendLine(indent + "{");
            EmitFactoryBody(directive.Children, indent + "    ",
                AddLocals(localNames, item, directive.IndexName));
            _sb.AppendLine(indent + "});");
            _sb.AppendLine(indent + parentName + ".RegisterGeneratedResource(" + field + ");");
            _sb.AppendLine(indent + field + ".AttachTo(" + parentName + ");");
        }

        private void EmitVIfChain(TemplateIfChainDirective chain, string indent, string parentName, IReadOnlyList<string> localNames)
        {
            string accumulated = null;
            foreach (var branch in chain.Branches)
            {
                var field = "_vif" + _vifIndex++;
                string condition;
                if (branch.IsElse)
                    condition = accumulated == null ? "true" : "!(" + accumulated + ")";
                else if (accumulated == null)
                    condition = branch.Condition ?? "false";
                else
                    condition = "!(" + accumulated + ") && (" + (branch.Condition ?? "false") + ")";

                accumulated = accumulated == null
                    ? "(" + (branch.Condition ?? "false") + ")"
                    : accumulated + " || (" + (branch.Condition ?? "false") + ")";

                _sb.AppendLine(indent + field + " = new ShowNode(" + condition + ", () =>");
                _sb.AppendLine(indent + "{");
                EmitFactoryBody(branch.Children, indent + "    ", localNames);
                _sb.AppendLine(indent + "});");
                _sb.AppendLine(indent + parentName + ".RegisterGeneratedResource(" + field + ");");
                _sb.AppendLine(indent + field + ".AttachTo(" + parentName + ");");
            }
        }

        private void EmitFactoryBody(List<SqxNode> nodes, string indent, IReadOnlyList<string> localNames)
        {
            var content = nodes.Where(node => !IsWrapperExpression(node)).ToList();
            if (content.Count == 0)
            {
                _sb.AppendLine(indent + "return null;");
                return;
            }

            if (content.Count == 1)
            {
                var rootName = EmitFactoryRoot(content[0], indent, localNames);
                if (!string.IsNullOrWhiteSpace(_doc.StyleCode))
                    _sb.AppendLine(indent + "ApplyComponentStyles(" + rootName + ");");
                _sb.AppendLine(indent + "return " + rootName + ";");
                return;
            }

            var fragmentName = NextVariable();
            _sb.AppendLine(indent + "var " + fragmentName + " = new View();");
            EmitNodes(content, indent, fragmentName, localNames);
            if (!string.IsNullOrWhiteSpace(_doc.StyleCode))
                _sb.AppendLine(indent + "ApplyComponentStyles(" + fragmentName + ");");
            _sb.AppendLine(indent + "return " + fragmentName + ";");
        }

        private string EmitFactoryRoot(SqxNode node, string indent, IReadOnlyList<string> localNames)
        {
            if (node is SqxElement element)
            {
                if (!_catalog.IsDirective(element.TagName))
                    return EmitControl(element, indent, localNames);
                var wrapper = NextVariable();
                _sb.AppendLine(indent + "var " + wrapper + " = new View();");
                EmitNodes(new List<SqxNode> { node }, indent, wrapper, localNames);
                return wrapper;
            }
            if (node is SqxText text)
                return EmitText(text.Text, indent);
            if (node is SqxExpression expression)
                return EmitExpressionText(expression.Expression, indent, localNames);

            // Vue 专属指令作为工厂根：用 View 包装，使其可作为 Element 返回。
            if (node is TemplateForDirective or TemplateIfChainDirective)
            {
                var wrapper = NextVariable();
                _sb.AppendLine(indent + "var " + wrapper + " = new View();");
                EmitNodes(new List<SqxNode> { node }, indent, wrapper, localNames);
                return wrapper;
            }

            var fallback = NextVariable();
            _sb.AppendLine(indent + "var " + fallback + " = new View();");
            return fallback;
        }

        private string EmitText(string value, string indent)
        {
            var variableName = NextVariable();
            _sb.AppendLine(indent + "var " + variableName + " = new Square.Controls.Text(\"" + Escape(NormalizeText(value)) + "\");");
            return variableName;
        }

        private string EmitExpressionText(string expression, string indent, IReadOnlyList<string> localNames)
        {
            var variableName = NextVariable();
            _sb.AppendLine(indent + "var " + variableName + " = new Square.Controls.Text();");
            if (IsLocalExpression(expression, localNames))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"TextContent\", (" + expression + ")?.ToString() ?? \"\");");
            else
                _sb.AppendLine(indent + variableName + ".BindProperty(\"TextContent\", " + expression + ");");
            return variableName;
        }

        private void EmitScript(string scriptCode)
        {
            if (string.IsNullOrWhiteSpace(scriptCode)) return;
            _sb.AppendLine();
            _sb.AppendLine("    #region Script");
            if (!string.IsNullOrWhiteSpace(_doc.SourcePath))
                _sb.AppendLine("#line 1 \"" + Escape(_doc.SourcePath) + "\"");
            foreach (var line in scriptCode.Split('\n'))
                _sb.AppendLine("    " + line.TrimEnd('\r'));
            if (!string.IsNullOrWhiteSpace(_doc.SourcePath))
                _sb.AppendLine("#line default");
            _sb.AppendLine("    #endregion");
        }

        private static (IReadOnlyList<string> Usings, string Body) SplitScriptUsings(string scriptCode)
        {
            if (string.IsNullOrEmpty(scriptCode)) return ([], "");

            var usings = new List<string>();
            var lines = scriptCode.Split('\n');
            var beforeMembers = true;
            var inBlockComment = false;
            for (var i = 0; i < lines.Length && beforeMembers; i++)
            {
                var trimmed = lines[i].Trim().TrimEnd('\r');
                if (inBlockComment)
                {
                    if (trimmed.Contains("*/", StringComparison.Ordinal)) inBlockComment = false;
                    continue;
                }
                if (trimmed.StartsWith("/*", StringComparison.Ordinal))
                {
                    inBlockComment = !trimmed.Contains("*/", StringComparison.Ordinal);
                    continue;
                }
                if (trimmed.Length == 0 || trimmed.StartsWith("//", StringComparison.Ordinal)) continue;
                if (trimmed.StartsWith("using ", StringComparison.Ordinal) &&
                    trimmed.EndsWith(";", StringComparison.Ordinal))
                {
                    usings.Add(trimmed);
                    lines[i] = "";
                    continue;
                }
                beforeMembers = false;
            }

            return (usings, string.Join("\n", lines));
        }

        private void EmitStyleSupport()
        {
            if (string.IsNullOrWhiteSpace(_doc.StyleCode)) return;
            var css = _doc.StyleCode.Replace("\"", "\"\"");
            _sb.AppendLine();
            _sb.AppendLine("    private static readonly Square.CSS.Ast.CssStyleSheet ComponentStyleSheet =");
            _sb.AppendLine("        new Square.CSS.Engine.CssParser(new Square.CSS.Tokenizer.CssTokenizer(@\"" + css + "\").Tokenize()).Parse();");
            _sb.AppendLine();
            _sb.AppendLine("    private static void ApplyComponentStyles(Element root)");
            _sb.AppendLine("    {");
            _sb.AppendLine("        var engine = new Square.CSS.Engine.CssEngine();");
            _sb.AppendLine("        engine.LoadStyleSheet(ComponentStyleSheet);");
            _sb.AppendLine("        engine.ApplyStylesToTree(root);");
            _sb.AppendLine("    }");
        }

        private string NextVariable() => "_v" + _varCounter++;

        private static bool IsLocalExpression(string expression, IReadOnlyList<string> localNames)
        {
            if (localNames.Count == 0 || string.IsNullOrWhiteSpace(expression)) return false;
            var value = expression.Trim();
            foreach (var localName in localNames)
                if (value == localName || value.StartsWith(localName + ".", StringComparison.Ordinal) ||
                    value.StartsWith(localName + "[", StringComparison.Ordinal)) return true;
            return false;
        }

        private static bool IsWrapperExpression(SqxNode node)
        {
            if (node is not SqxExpression expression) return false;
            var value = expression.Expression.Trim();
            return value.EndsWith("=>", StringComparison.Ordinal) || value == "}";
        }

        private static bool IsTemplateFragment(SqxElement element) =>
            string.Equals(element.TagName, "Fragment", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(element.TagName, "template", StringComparison.OrdinalIgnoreCase);

        private static SqxAttribute FindAttr(SqxElement element, string name) =>
            element.Attributes.FirstOrDefault(attribute => string.Equals(attribute.Name, name, StringComparison.OrdinalIgnoreCase));

        private static bool HasObjectBindings(IEnumerable<SqxNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is SqxElement element)
                {
                    if (element.Attributes.Any(attribute =>
                        attribute.Name is "__sqv_bind_object" or "__sqv_on_object" ||
                        attribute.IsDynamicProperty || attribute.IsDynamicEvent))
                        return true;
                    if (HasObjectBindings(element.Children)) return true;
                }
                else if (node is TemplateForDirective forDirective)
                {
                    if (HasObjectBindings(forDirective.Children)) return true;
                }
                else if (node is TemplateIfChainDirective ifDirective)
                {
                    foreach (var branch in ifDirective.Branches)
                        if (HasObjectBindings(branch.Children)) return true;
                }
            }
            return false;
        }

        private static bool IsSimpleMemberExpression(string expression)
        {
            if (string.IsNullOrWhiteSpace(expression)) return false;
            foreach (var part in expression.Split('.'))
            {
                if (part.Length == 0 || !(char.IsLetter(part[0]) || part[0] == '_')) return false;
                for (var i = 1; i < part.Length; i++)
                    if (!(char.IsLetterOrDigit(part[i]) || part[i] == '_')) return false;
            }
            return true;
        }

        private static string NormalizeText(string value)
        {
            if (string.IsNullOrWhiteSpace(value)) return "";
            return value.Trim();
        }

        internal void EmitOptionalFactory(List<SqxNode> nodes, string indent, IReadOnlyList<string> localNames)
        {
            EmitFactoryBody(nodes, indent, localNames);
        }

        private static IReadOnlyList<string> AddLocals(IReadOnlyList<string> locals, params string[] names)
        {
            var result = new List<string>(locals);
            foreach (var name in names)
                if (!string.IsNullOrWhiteSpace(name) && !result.Contains(name, StringComparer.Ordinal)) result.Add(name);
            return result;
        }

        private sealed class SlotGroup
        {
            public SlotGroup(string name, bool nameIsExpression, TemplateSlotScope scope, List<SqxNode> nodes)
            {
                Name = name;
                NameIsExpression = nameIsExpression;
                Scope = scope;
                Nodes = nodes;
            }

            public string Name { get; }
            public bool NameIsExpression { get; }
            public TemplateSlotScope Scope { get; }
            public List<SqxNode> Nodes { get; }
        }

        private static string[] Split(string value, char separator) =>
            value == null ? Array.Empty<string>() : value.Split(separator);

        private static string Escape(string value) =>
            value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");

        private static int StableSourceId(string value)
        {
            unchecked
            {
                var hash = 17;
                foreach (var character in value ?? "") hash = hash * 31 + character;
                return hash;
            }
        }

        private void EmitSourceMappedLine(string indent, int line, string code)
        {
            if (!string.IsNullOrWhiteSpace(_doc.SourcePath) && line > 0)
                _sb.AppendLine("#line " + line + " \"" + Escape(_doc.SourcePath) + "\"");
            _sb.AppendLine(indent + code);
            if (!string.IsNullOrWhiteSpace(_doc.SourcePath) && line > 0)
                _sb.AppendLine("#line default");
        }

        private static string MapTagName(string tag) => tag.ToLowerInvariant() switch
        {
            "view" => "Square.Controls.View",
            "scrollviewer" => "Square.Controls.ScrollViewer",
            "popup" => "Square.Controls.Popup",
            "dialog" => "Square.Controls.Dialog",
            "menubar" => "Square.Controls.MenuBar",
            "menu" => "Square.Controls.Menu",
            "contextmenu" => "Square.Controls.ContextMenu",
            "menuitem" => "Square.Controls.MenuItem",
            "menuseparator" => "Square.Controls.MenuSeparator",
            "text" => "Square.Controls.Text",
            "fonticon" => "Square.Controls.FontIcon",
            "splitter" => "Square.Controls.Splitter",
            "list" => "Square.Controls.List",
            "virtuallist" => "Square.Controls.VirtualList",
            "listitem" => "Square.Controls.ListItem",
            "tree" => "Square.Controls.Tree",
            "virtualtree" => "Square.Controls.VirtualTree",
            "treeitem" => "Square.Controls.TreeItem",
            "swiper" => "Square.Controls.Swiper",
            "button" => "Square.Controls.Button",
            "input" => "Square.Controls.Input",
            "textarea" => "Square.Controls.TextArea",
            "checkbox" => "Square.Controls.CheckBox",
            "radio" => "Square.Controls.Radio",
            "select" => "Square.Controls.Select",
            "image" => "Square.Controls.Image",
            "canvas" => "Square.Controls.Canvas",
            "svg" => "Square.UI.Svg.SVGSVGElement",
            "g" => "Square.UI.Svg.SVGGElement",
            "path" => "Square.UI.Svg.SVGPathElement",
            "rect" => "Square.UI.Svg.SVGRectElement",
            "circle" => "Square.UI.Svg.SVGCircleElement",
            "ellipse" => "Square.UI.Svg.SVGEllipseElement",
            "line" => "Square.UI.Svg.SVGLineElement",
            "polyline" => "Square.UI.Svg.SVGPolylineElement",
            "polygon" => "Square.UI.Svg.SVGPolygonElement",
            "titlebar" => "Square.Controls.TitleBar",
            "link" => "Square.Controls.Link",
            _ => tag
        };

        private static bool IsBuiltInTag(string tag) => tag.ToLowerInvariant() is "view" or "scrollviewer" or "popup" or "dialog" or
            "menubar" or "menu" or "contextmenu" or "menuitem" or "menuseparator" or "text" or "fonticon" or "splitter" or "list" or "virtuallist" or "listitem" or "tree" or "virtualtree" or "treeitem" or "swiper" or
            "button" or "input" or "textarea" or "checkbox" or "radio" or "select" or "image" or "canvas" or "titlebar" or "link" or
            "svg" or "g" or "path" or "rect" or "circle" or "ellipse" or "line" or "polyline" or "polygon";

        private static bool IsTitleBar(string tag) =>
            string.Equals(tag, "titlebar", StringComparison.OrdinalIgnoreCase);

        private static bool RequiresBuildAfterAttach(string tag) =>
            !IsBuiltInTag(tag) || IsTitleBar(tag);

        private static bool IsTextContentElement(string tag) => tag.ToLowerInvariant() is "text" or "button" or "link" or "listitem" or "treeitem";

        private static string MapPropName(string name) => name.ToLowerInvariant() switch
        {
            "text" => "TextContent",
            "glyph" => "Glyph",
            "icon" => "Icon",
            "font-family" => "FontFamily",
            "minimum" => "Minimum",
            "maximum" => "Maximum",
            "vertical" => "IsVertical",
            "reversed" => "IsReversed",
            "value" => "Value",
            "checked" => "IsChecked",
            "disabled" => "IsDisabled",
            "placeholder" => "Placeholder",
            "source" => "Source",
            "image" => "ImageContent",
            "group" => "GroupName",
            "shortcut" => "ShortcutText",
            "checkable" => "IsCheckable",
            "stays-open-on-click" => "StaysOpenOnClick",
            "options" => "Options",
            "items" => "Items",
            "selected-index" => "SelectedIndex",
            "item-height" => "ItemHeight",
            "overscan-count" => "OverscanCount",
            "indent-size" => "IndentSize",
            "expanded" => "IsExpanded",
            "loop" => "Loop",
            "to" => "To",
            "href" => "Href",
            "marker" => "Marker",
            "replace" => "Replace",
            "color" => "Color",
            "background" => "Background",
            "underline" => "Underline",
            "type" => "Type",
            "viewbox" => "ViewBox",
            "x" => "X",
            "y" => "Y",
            "width" => "Width",
            "height" => "Height",
            "rx" => "RadiusX",
            "ry" => "RadiusY",
            "cx" => "CenterX",
            "cy" => "CenterY",
            "r" => "Radius",
            "x1" => "X1",
            "y1" => "Y1",
            "x2" => "X2",
            "y2" => "Y2",
            "points" => "Points",
            "d" => "Data",
            "transform" => "Transform",
            "fill" => "Fill",
            "stroke" => "Stroke",
            "stroke-width" => "StrokeWidth",
            "opacity" => "Opacity",
            "fill-opacity" => "FillOpacity",
            "stroke-opacity" => "StrokeOpacity",
            _ => name
        };

        private sealed class RefInfo
        {
            public string Name { get; }
            public string TypeName { get; }

            public RefInfo(string name, string typeName)
            {
                Name = name;
                TypeName = typeName;
            }
        }
    }
}
