using System.Text;
using Microsoft.CodeAnalysis;
using Square.Compiler.Directives;
using Square.Compiler.LanguageServices;
using Square.Compiler.Parser;
using Square.Compiler.Template;
using Square.Compiler.Template.Compatibility;

namespace Square.Compiler.Emit
{
    internal sealed class ComponentEmitter
    {
        private readonly TemplateDocument _doc;
        private readonly string _namespace;
        private readonly StringBuilder _sb = new StringBuilder();
        private readonly List<RefInfo> _refs = new List<RefInfo>();
        private readonly DirectiveCatalog _catalog;
        private readonly TemplateCatalog _templateCatalog;
        private readonly IReadOnlyDictionary<string, TemplateComponentEventDescriptor[]> _eventContracts;
        private readonly Dictionary<string, string> _variableTags = new Dictionary<string, string>();
        private DirectiveEmitPipeline _pipeline;
        private int _vforIndex;
        private int _vifIndex;
        private int _varCounter;
        private int _slotCounter;
        private bool _hasObjectBindings;

        public ComponentEmitter(
            SqxDocument doc,
            string namespaceName = "Square.Sample",
            DirectiveCatalog catalog = null,
            IReadOnlyDictionary<string, TemplateComponentEventDescriptor[]> eventContracts = null)
            : this(TemplateDocument.From(doc), namespaceName, catalog, eventContracts)
        {
        }

        public ComponentEmitter(
            TemplateDocument doc,
            string namespaceName = "Square.Sample",
            DirectiveCatalog catalog = null,
            IReadOnlyDictionary<string, TemplateComponentEventDescriptor[]> eventContracts = null)
        {
            _doc = doc;
            _catalog = catalog ?? DirectiveCatalog.BuiltIn;
            _templateCatalog = TemplateCatalog.BuiltIn;
            _eventContracts = eventContracts ??
                new Dictionary<string, TemplateComponentEventDescriptor[]>(StringComparer.Ordinal);
            _namespace = !string.IsNullOrWhiteSpace(doc.Namespace)
                ? doc.Namespace
                : string.IsNullOrWhiteSpace(namespaceName) ? "Square.Sample" : namespaceName;
        }

        public string Emit()
        {
            ResetState();
            var roots = GetTemplateRoots();
            CollectRefs(roots);
            _hasObjectBindings = HasObjectBindings(roots);
            var (scriptUsings, scriptBody) = GetScriptParts();

            _sb.AppendLine("// <auto-generated/>");
            _sb.AppendLine("#nullable enable");
            _sb.AppendLine();
            _sb.AppendLine("using Square.UI;");
            _sb.AppendLine("using Square.Events;");
            _sb.AppendLine("using Square.Runtime;");
            _sb.AppendLine("using Square.Runtime.Binding;");
            _sb.AppendLine("using Square.Graphics;");
            _sb.AppendLine("using Square.Controls;");
            _sb.AppendLine("using Square.Controls.Primitives;");
            foreach (var usingDirective in scriptUsings)
                _sb.AppendLine(usingDirective);
            _sb.AppendLine();
            _sb.AppendLine("namespace " + _namespace + ";");
            _sb.AppendLine();
            _sb.AppendLine(_doc.Access + " partial class " + _doc.Name + " : UIElement");
            _sb.AppendLine("#if DEBUG");
            _sb.AppendLine("    , Square.Hosting.ISquareHotReloadComponent");
            _sb.AppendLine("#endif");
            _sb.AppendLine("{");

            EmitFields();
            _sb.AppendLine("#if DEBUG");
            _sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
            _sb.AppendLine("#endif");
            _sb.AppendLine("    public override void BuildElementTree()");
            _sb.AppendLine("    {");
            _sb.AppendLine("        if (_visualTreeBuilt) return;");
            _sb.AppendLine("        _visualTreeBuilt = true;");
            EmitNodes(roots, "        ", "this", Array.Empty<string>());
            _sb.AppendLine("        ApplyComponentStyles(this);");
            _sb.AppendLine("#if DEBUG");
            _sb.AppendLine("        _hotReloadVersion = CurrentHotReloadVersion();");
            _sb.AppendLine("#endif");
            _sb.AppendLine("    }");

            EmitScript(scriptBody);
            EmitStyleSupport();
            EmitHotReloadSupport();
            _sb.AppendLine("}");
            return _sb.ToString();
        }

        private List<SqxNode> GetTemplateRoots()
        {
            if (_doc.Ir == null || _doc.Syntax?.Template == null) return _doc.Roots;
            return TemplateIrCompatibilityAdapter.ToSqxNodes(
                _doc.Ir,
                _doc.Syntax.SourceText,
                _doc.Syntax.Dialect,
                _doc.Syntax.Template.ContentRange.Offset);
        }

        private void ResetState()
        {
            _varCounter = 0;
            _slotCounter = 0;
            _hasObjectBindings = false;
            _vforIndex = 0;
            _vifIndex = 0;
            _refs.Clear();
            _variableTags.Clear();
            _sb.Clear();
            _pipeline = new DirectiveEmitPipeline(
                _sb,
                _catalog,
                EmitNodes,
                EmitFactoryBody,
                EmitAttribute,
                NextVariable);
            _pipeline.ResetFieldIndexes();
        }

        private void CollectRefs(List<SqxNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is SqxElement element)
                {
                    var refAttr = FindAttr(element, "ref");
                    if (refAttr != null && !string.IsNullOrWhiteSpace(refAttr.RawValue) &&
                        !_refs.Exists(item => item.Name == refAttr.RawValue))
                    {
                        _refs.Add(new RefInfo(refAttr.RawValue, MapTagName(element.TagName)));
                    }
                    CollectRefs(element.Children);
                }
                else if (node is TemplateForDirective forDirective)
                    CollectRefs(forDirective.Children);
                else if (node is TemplateIfChainDirective ifChain)
                    foreach (var branch in ifChain.Branches)
                        CollectRefs(branch.Children);
            }
        }

        private void EmitFields()
        {
            _sb.AppendLine("    private bool _visualTreeBuilt;");
            foreach (var item in _refs)
                _sb.AppendLine("    internal " + item.TypeName + " " + item.Name + " = null!;");
            _sb.AppendLine("#if DEBUG");
            _sb.AppendLine("    private long _hotReloadVersion;");
            _sb.AppendLine("#endif");
            _sb.AppendLine();
        }

        private void EmitNodes(List<SqxNode> nodes, string indent, string parentName, IReadOnlyList<string> localNames)
        {
            foreach (var node in nodes)
            {
                if (IsWrapperExpression(node)) continue;

                if (node is SqxText text)
                {
                    if (string.IsNullOrWhiteSpace(text.Text)) continue;
                    var textName = EmitText(text.Text, indent);
                    _sb.AppendLine(indent + parentName + ".Children.Add(" + textName + ");");
                }
                else if (node is SqxExpression expression)
                {
                    var textName = EmitExpressionText(expression.Expression, indent, localNames);
                    _sb.AppendLine(indent + parentName + ".Children.Add(" + textName + ");");
                }
                else if (node is SqxElement element)
                {
                    if (IsTemplateFragment(element))
                    {
                        EmitNodes(element.Children, indent, parentName, localNames);
                        continue;
                    }

                    // Catalog-driven structural directives (Show/For/Switch/Slot/Router/…)
                    if (_catalog.IsDirective(element.TagName))
                    {
                        _pipeline.TryEmit(element, indent, parentName, localNames);
                        continue;
                    }

                    var elementName = EmitControl(element, indent, localNames, parentName);
                    _sb.AppendLine(indent + parentName + ".Children.Add(" + elementName + ");");
                    if (RequiresBuildAfterAttach(element.TagName))
                        _sb.AppendLine(indent + elementName + ".BuildElementTree();");
                }
                else if (node is TemplateForDirective forDirective)
                {
                    EmitVFor(forDirective, indent, parentName, localNames);
                }
                else if (node is TemplateIfChainDirective ifChain)
                {
                    EmitVIfChain(ifChain, indent, parentName, localNames);
                }
            }
        }

        private string EmitControl(SqxElement element, string indent, IReadOnlyList<string> localNames, string parentName = null)
        {
            var refAttr = FindAttr(element, "ref");
            var isRef = refAttr != null && !string.IsNullOrWhiteSpace(refAttr.RawValue);
            var variableName = isRef ? refAttr.RawValue : NextVariable();
            var tagName = MapTagName(element.TagName);
            var isCustomComponent = !IsBuiltInTag(element.TagName);
            var usesSlots = isCustomComponent || IsBuiltInSlotHost(element.TagName);
            _variableTags[variableName] = element.TagName;

            if (isRef)
                _sb.AppendLine(indent + variableName + " = new " + tagName + "();");
            else
                _sb.AppendLine(indent + "var " + variableName + " = new " + tagName + "();");
            _sb.AppendLine(indent + variableName + ".SetDebugInfo(ElementDebugInfo.Create(" +
                StableSourceId(_doc.SourcePath) + ", " + element.Line + ", " + element.Column + ", " +
                element.Line + ", " + (element.Column + Math.Max(1, element.TagName.Length)) +
                ", \"" + Escape(element.TagName) + "\", \"" + Escape(_doc.Name) + "\", sourcePath: \"" +
                Escape(_doc.SourcePath) + "\"));");

            // Initialize properties before events, then let v-model write back before user handlers.
            // Property hooks may emit events, so model listeners must not exist during initialization.
            foreach (var attribute in element.Attributes.Where(attribute => !IsEventAttribute(attribute)))
                EmitAttribute(variableName, attribute, indent, localNames);
            foreach (var attribute in element.Attributes.Where(attribute => attribute.IsModelEvent))
                EmitAttribute(variableName, attribute, indent, localNames);
            foreach (var attribute in element.Attributes.Where(attribute => IsEventAttribute(attribute) && !attribute.IsModelEvent))
                EmitAttribute(variableName, attribute, indent, localNames);

            if (usesSlots)
            {
                EmitComponentSlots(element, variableName, indent, localNames);
            }
            else if (!EmitTextContent(element, variableName, indent, localNames))
                EmitNodes(element.Children, indent, variableName, localNames);

            return variableName;
        }

        private static bool IsEventAttribute(SqxAttribute attribute) =>
            attribute.IsModelEvent || attribute.IsDynamicEvent ||
            attribute.Name == "__sqv_on_object" ||
            attribute.IsExpression && attribute.Name.StartsWith("on", StringComparison.OrdinalIgnoreCase);

        private void EmitAttribute(string variableName, SqxAttribute attribute, string indent, IReadOnlyList<string> localNames)
        {
            if (attribute.Name == "ref" || attribute.Name == "slot") return;

            if (attribute.IsDynamicProperty)
            {
                _sb.AppendLine(indent + variableName + ".RegisterGeneratedResource(SqvObjectBinding.BindProperty(" + variableName + ", " + attribute.ArgumentExpression + ", " + attribute.RawValue + "));");
                return;
            }

            if (attribute.IsDynamicEvent)
            {
                _sb.AppendLine(indent + variableName + ".RegisterGeneratedResource(SqvObjectBinding.BindEvent(" + variableName + ", " + attribute.ArgumentExpression + ", " + attribute.RawValue + "));");
                return;
            }

            if (attribute.Name == "__sqv_bind_object")
            {
                _sb.AppendLine(indent + variableName + ".RegisterGeneratedResource(SqvObjectBinding.BindProperties(" + variableName + ", " + attribute.RawValue + "));");
                return;
            }

            if (attribute.Name == "__sqv_on_object")
            {
                _sb.AppendLine(indent + variableName + ".RegisterGeneratedResource(SqvObjectBinding.BindEvents(" + variableName + ", " + attribute.RawValue + "));");
                return;
            }

            if (attribute.Name == "class" && !attribute.IsExpression)
            {
                foreach (var className in Split(attribute.RawValue, ' '))
                    if (!string.IsNullOrWhiteSpace(className))
                        _sb.AppendLine(indent + variableName + ".ClassList.Add(\"" + Escape(className) + "\");");
                return;
            }

            if (attribute.Name == "style" && !attribute.IsExpression)
            {
                _sb.AppendLine(indent + variableName + ".Style.CssText = \"" + Escape(attribute.RawValue) + "\";");
                return;
            }

            if (attribute.IsExpression)
            {
                if (attribute.Name.StartsWith("on", StringComparison.OrdinalIgnoreCase))
                {
                    var eventName = attribute.Name.Substring(2).ToLowerInvariant();
                    var componentEvent = FindComponentEvent(variableName, eventName);
                    var eventArgument = componentEvent == null
                        ? "\"" + eventName + "\""
                        : MapTagName(_variableTags[variableName]) + "." + componentEvent.MemberName;
                    EmitSourceMappedLine(indent, attribute.Line,
                        variableName + ".RegisterGeneratedResource(" + variableName + ".Listen(" +
                        eventArgument + ", " + attribute.RawValue + "));");
                }
                else
                {
                    var propertyName = MapPropName(attribute.Name);
                    if (IsLocalExpression(attribute.RawValue, localNames))
                        EmitSourceMappedLine(indent, attribute.Line,
                            variableName + ".SetProperty(\"" + propertyName + "\", " + attribute.RawValue + ");");
                    else
                        EmitSourceMappedLine(indent, attribute.Line,
                            variableName + ".BindProperty(\"" + propertyName + "\", " + attribute.RawValue + ");");
                }
                return;
            }

            var propName = MapPropName(attribute.Name);
            var rawValue = attribute.RawValue ?? "";
            if (attribute.Name.Equals("disabled", StringComparison.OrdinalIgnoreCase) && string.IsNullOrEmpty(rawValue))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", true);");
            else if (bool.TryParse(rawValue, out var boolValue))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", " + boolValue.ToString().ToLowerInvariant() + ");");
            else if (int.TryParse(rawValue, out var intValue))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", " + intValue + ");");
            else
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", \"" + Escape(rawValue) + "\");");
        }

        private bool EmitTextContent(SqxElement element, string variableName, string indent, IReadOnlyList<string> localNames)
        {
            if (!IsTextContentElement(element.TagName)) return false;
            if (FindAttr(element, "text") != null) return true;

            var content = element.Children.Where(node => !IsWrapperExpression(node)).ToList();
            if (content.Count == 0) return true;
            if (content.All(node => node is SqxText))
            {
                var value = string.Concat(content.Cast<SqxText>().Select(node => node.Text));
                _sb.AppendLine(indent + variableName + ".SetProperty(\"TextContent\", \"" + Escape(NormalizeText(value)) + "\");");
                return true;
            }
            if (content.Count == 1 && content[0] is SqxExpression expression)
            {
                if (IsLocalExpression(expression.Expression, localNames))
                    _sb.AppendLine(indent + variableName + ".SetProperty(\"TextContent\", (" + expression.Expression + ")?.ToString() ?? \"\");");
                else
                    _sb.AppendLine(indent + variableName + ".BindProperty(\"TextContent\", " + expression.Expression + ");");
                return true;
            }
            if (content.All(node => node is SqxText or SqxExpression))
            {
                var parts = content.Select(node => node switch
                {
                    SqxText text => "\"" + Escape(text.Text) + "\"",
                    SqxExpression expression => "((" + expression.Expression + ")?.ToString() ?? \"\")",
                    _ => "\"\""
                });
                var sources = content.OfType<SqxExpression>()
                    .Select(expression => expression.Expression.Trim())
                    .Where(IsSimpleMemberExpression)
                    .Distinct(StringComparer.Ordinal)
                    .ToList();
                var sourceArgs = sources.Count == 0 ? "" : ", " + string.Join(", ", sources);
                _sb.AppendLine(indent + variableName + ".BindProperty(\"TextContent\", () => " +
                    string.Join(" + ", parts) + sourceArgs + ");");
                return true;
            }
            return false;
        }

        private void EmitComponentSlots(SqxElement element, string variableName, string indent, IReadOnlyList<string> localNames)
        {
            var groups = new List<SlotGroup>();
            foreach (var child in element.Children)
            {
                if (IsWrapperExpression(child)) continue;
                var slotName = "";
                var slotNameIsExpression = false;
                TemplateSlotScope slotScope = null;
                var slotNodes = new List<SqxNode> { child };
                if (child is SqxElement childElement)
                {
                    var slotAttribute = FindAttr(childElement, "slot");
                    slotName = slotAttribute?.RawValue ?? "";
                    slotNameIsExpression = slotAttribute?.IsExpression == true;
                    slotScope = childElement.SlotScope;
                    if (IsTemplateFragment(childElement))
                        slotNodes = childElement.Children;
                }

                var groupIndex = groups.FindIndex(group =>
                    group.NameIsExpression == slotNameIsExpression &&
                    string.Equals(group.Name, slotName, StringComparison.Ordinal) &&
                    ReferenceEquals(group.Scope, slotScope));
                if (groupIndex < 0)
                {
                    groups.Add(new SlotGroup(slotName, slotNameIsExpression, slotScope, new List<SqxNode>(slotNodes)));
                }
                else
                {
                    groups[groupIndex].Nodes.AddRange(slotNodes);
                }
            }

            foreach (var group in groups)
            {
                var parentParameter = "__slotParent" + _slotCounter++;
                var name = group.NameIsExpression ? group.Name : "\"" + Escape(group.Name) + "\"";
                var parameters = group.Scope == null
                    ? parentParameter
                    : "(" + parentParameter + ", __slotProps)";
                _sb.AppendLine(indent + variableName + ".Slots.Set(" + name + ", " + parameters + " =>");
                _sb.AppendLine(indent + "{");
                var scopeLocals = localNames;
                if (!string.IsNullOrWhiteSpace(group.Scope?.WholePropsName))
                {
                    _sb.AppendLine(indent + "    var " + group.Scope.WholePropsName + " = __slotProps;");
                    scopeLocals = AddLocals(scopeLocals, group.Scope.WholePropsName);
                }
                else if (group.Scope != null)
                {
                    foreach (var binding in group.Scope.Properties)
                    {
                        _sb.AppendLine(indent + "    var " + binding.LocalName + " = __slotProps.Get<" + binding.TypeName + ">(\"" + Escape(binding.PropertyName) + "\");");
                        scopeLocals = AddLocals(scopeLocals, binding.LocalName);
                    }
                }
                EmitNodes(group.Nodes, indent + "    ", parentParameter, scopeLocals);
                _sb.AppendLine(indent + "});");
            }
        }

        private void EmitVFor(TemplateForDirective directive, string indent, string parentName, IReadOnlyList<string> localNames)
        {
            var field = "_vfor" + _vforIndex++;
            var item = directive.ItemName;
            var hasIndex = !string.IsNullOrEmpty(directive.IndexName);
            var lambda = hasIndex ? "(" + item + ", " + directive.IndexName + ")" : item;
            var keySelector = string.IsNullOrWhiteSpace(directive.KeyExpression)
                ? ""
                : lambda + " => " + directive.KeyExpression + ", ";
            _sb.AppendLine(indent + "var " + field + " = ForNode.Create(" + directive.SourceExpression + ", " + keySelector + lambda + " =>");
            _sb.AppendLine(indent + "{");
            EmitFactoryBody(directive.Children, indent + "    ",
                AddLocals(localNames, item, directive.IndexName));
            _sb.AppendLine(indent + "});");
            _sb.AppendLine(indent + parentName + ".RegisterGeneratedResource(" + field + ");");
            _sb.AppendLine(indent + field + ".AttachTo(" + parentName + ");");
        }

        private void EmitVIfChain(TemplateIfChainDirective chain, string indent, string parentName, IReadOnlyList<string> localNames)
        {
            string accumulated = null;
            foreach (var branch in chain.Branches)
            {
                var field = "_vif" + _vifIndex++;
                string condition;
                if (branch.IsElse)
                    condition = accumulated == null ? "true" : "!(" + accumulated + ")";
                else if (accumulated == null)
                    condition = branch.Condition ?? "false";
                else
                    condition = "!(" + accumulated + ") && (" + (branch.Condition ?? "false") + ")";

                accumulated = accumulated == null
                    ? "(" + (branch.Condition ?? "false") + ")"
                    : accumulated + " || (" + (branch.Condition ?? "false") + ")";

                _sb.AppendLine(indent + "var " + field + " = new ShowNode(" + condition + ", () =>");
                _sb.AppendLine(indent + "{");
                EmitFactoryBody(branch.Children, indent + "    ", localNames);
                _sb.AppendLine(indent + "});");
                _sb.AppendLine(indent + parentName + ".RegisterGeneratedResource(" + field + ");");
                _sb.AppendLine(indent + field + ".AttachTo(" + parentName + ");");
            }
        }

        private void EmitFactoryBody(List<SqxNode> nodes, string indent, IReadOnlyList<string> localNames)
        {
            var content = nodes.Where(node => !IsWrapperExpression(node)).ToList();
            if (content.Count == 0)
            {
                _sb.AppendLine(indent + "return null;");
                return;
            }

            if (content.Count == 1)
            {
                var rootName = EmitFactoryRoot(content[0], indent, localNames);
                _sb.AppendLine(indent + "ApplyComponentStyles(" + rootName + ");");
                _sb.AppendLine(indent + "return " + rootName + ";");
                return;
            }

            var fragmentName = NextVariable();
            _sb.AppendLine(indent + "var " + fragmentName + " = new View();");
            EmitNodes(content, indent, fragmentName, localNames);
            _sb.AppendLine(indent + "ApplyComponentStyles(" + fragmentName + ");");
            _sb.AppendLine(indent + "return " + fragmentName + ";");
        }

        private string EmitFactoryRoot(SqxNode node, string indent, IReadOnlyList<string> localNames)
        {
            if (node is SqxElement element)
            {
                if (!_catalog.IsDirective(element.TagName))
                    return EmitControl(element, indent, localNames);
                var wrapper = NextVariable();
                _sb.AppendLine(indent + "var " + wrapper + " = new View();");
                EmitNodes(new List<SqxNode> { node }, indent, wrapper, localNames);
                return wrapper;
            }
            if (node is SqxText text)
                return EmitText(text.Text, indent);
            if (node is SqxExpression expression)
                return EmitExpressionText(expression.Expression, indent, localNames);

            // Vue 专属指令作为工厂根：用 View 包装，使其可作为 Element 返回。
            if (node is TemplateForDirective or TemplateIfChainDirective)
            {
                var wrapper = NextVariable();
                _sb.AppendLine(indent + "var " + wrapper + " = new View();");
                EmitNodes(new List<SqxNode> { node }, indent, wrapper, localNames);
                return wrapper;
            }

            var fallback = NextVariable();
            _sb.AppendLine(indent + "var " + fallback + " = new View();");
            return fallback;
        }

        private string EmitText(string value, string indent)
        {
            var variableName = NextVariable();
            _sb.AppendLine(indent + "var " + variableName + " = new Square.Controls.Text(\"" + Escape(NormalizeText(value)) + "\");");
            return variableName;
        }

        private string EmitExpressionText(string expression, string indent, IReadOnlyList<string> localNames)
        {
            var variableName = NextVariable();
            _sb.AppendLine(indent + "var " + variableName + " = new Square.Controls.Text();");
            if (IsLocalExpression(expression, localNames))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"TextContent\", (" + expression + ")?.ToString() ?? \"\");");
            else
                _sb.AppendLine(indent + variableName + ".BindProperty(\"TextContent\", " + expression + ");");
            return variableName;
        }

        private void EmitScript(string scriptCode)
        {
            if (string.IsNullOrWhiteSpace(scriptCode)) return;
            _sb.AppendLine();
            _sb.AppendLine("    #region Script");
            if (!string.IsNullOrWhiteSpace(_doc.SourcePath))
                _sb.AppendLine("#line 1 \"" + Escape(_doc.SourcePath) + "\"");
            foreach (var line in scriptCode.Split('\n'))
                _sb.AppendLine("    " + line.TrimEnd('\r'));
            if (!string.IsNullOrWhiteSpace(_doc.SourcePath))
                _sb.AppendLine("#line default");
            _sb.AppendLine("    #endregion");
        }

        private (IReadOnlyList<string> Usings, string Body) GetScriptParts()
        {
            var script = _doc.Syntax?.Script;
            if (script == null) return (Array.Empty<string>(), string.Empty);

            var usings = script.CSharp.Usings
                .Select(directive => directive.WithoutTrivia().NormalizeWhitespace().ToFullString())
                .ToArray();
            var bodyText = script.ContentText.Trim();
            if (bodyText.Length == 0) return (usings, string.Empty);
            var trimStart = script.ContentText.IndexOf(bodyText, StringComparison.Ordinal);
            if (trimStart < 0) return (usings, bodyText);

            var lines = bodyText.Split('\n');
            foreach (var directive in script.CSharp.Usings)
            {
                var start = Math.Max(0, Math.Min(directive.Span.Start - trimStart, bodyText.Length));
                var end = Math.Max(start, Math.Min(directive.Span.End - trimStart, bodyText.Length));
                var startLine = GetLineIndex(bodyText, start);
                var endLine = GetLineIndex(bodyText, Math.Max(start, end - 1));
                for (var line = startLine; line <= endLine && line < lines.Length; line++) lines[line] = string.Empty;
            }
            return (usings, string.Join("\n", lines));
        }

        private static int GetLineIndex(string text, int position)
        {
            var line = 0;
            for (var index = 0; index < position && index < text.Length; index++)
                if (text[index] == '\n') line++;
            return line;
        }

        private void EmitStyleSupport()
        {
            var style = _doc.Syntax?.Style?.Css;
            _sb.AppendLine();
            _sb.AppendLine("#if DEBUG");
            _sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
            _sb.AppendLine("    private static Square.CSS.Ast.CssStyleSheet? CreateComponentStyleSheet() =>");
            _sb.AppendLine(style == null
                ? "        null;"
                : "        " + StyleAstRuntimeEmitter.Emit(style) + ";");
            _sb.AppendLine("#else");
            _sb.AppendLine("    private static readonly Square.CSS.Ast.CssStyleSheet? ComponentStyleSheet =");
            _sb.AppendLine(style == null
                ? "        null;"
                : "        " + StyleAstRuntimeEmitter.Emit(style) + ";");
            _sb.AppendLine("    private static Square.CSS.Ast.CssStyleSheet? CreateComponentStyleSheet() => ComponentStyleSheet;");
            _sb.AppendLine("#endif");
            _sb.AppendLine();
            _sb.AppendLine("#if DEBUG");
            _sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
            _sb.AppendLine("#endif");
            _sb.AppendLine("    private static void ApplyComponentStyles(Element root)");
            _sb.AppendLine("    {");
            _sb.AppendLine("        var styleSheet = CreateComponentStyleSheet();");
            _sb.AppendLine("        if (styleSheet == null) return;");
            _sb.AppendLine("        var engine = new Square.CSS.Engine.CssEngine();");
            _sb.AppendLine("        engine.LoadStyleSheet(styleSheet);");
            _sb.AppendLine("        root.RegisterGeneratedResource(engine.ApplyGeneratedStylesToTree(root));");
            _sb.AppendLine("    }");
        }

        private void EmitHotReloadSupport()
        {
            var template = _doc.Syntax?.Template?.ContentText ?? string.Empty;
            var style = _doc.Syntax?.Style?.ContentText ?? string.Empty;
            var version = StableVersion(template + "\0" + style);

            _sb.AppendLine();
            _sb.AppendLine("#if DEBUG");
            _sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
            _sb.AppendLine("    private static long CurrentHotReloadVersion() => " + version + "L;");
            _sb.AppendLine();
            _sb.AppendLine("    bool Square.Hosting.ISquareHotReloadComponent.HasHotReloadChanges =>");
            _sb.AppendLine("        _hotReloadVersion != CurrentHotReloadVersion();");
            _sb.AppendLine();
            _sb.AppendLine("    void Square.Hosting.ISquareHotReloadComponent.RebuildAfterHotReload()");
            _sb.AppendLine("    {");
            _sb.AppendLine("        PrepareGeneratedSubtreeRebuild();");
            _sb.AppendLine("        Slots.ResetRendered();");
            foreach (var item in _refs)
                _sb.AppendLine("        " + item.Name + " = null!;");
            _sb.AppendLine("        _visualTreeBuilt = false;");
            _sb.AppendLine("        try");
            _sb.AppendLine("        {");
            _sb.AppendLine("            BuildElementTree();");
            _sb.AppendLine("        }");
            _sb.AppendLine("        catch");
            _sb.AppendLine("        {");
            _sb.AppendLine("            PrepareGeneratedSubtreeRebuild();");
            _sb.AppendLine("            Slots.ResetRendered();");
            foreach (var item in _refs)
                _sb.AppendLine("            " + item.Name + " = null!;");
            _sb.AppendLine("            _visualTreeBuilt = false;");
            _sb.AppendLine("            throw;");
            _sb.AppendLine("        }");
            _sb.AppendLine("    }");
            _sb.AppendLine("#endif");
        }

        private string NextVariable() => "_v" + _varCounter++;

        private static bool IsLocalExpression(string expression, IReadOnlyList<string> localNames)
        {
            if (localNames.Count == 0 || string.IsNullOrWhiteSpace(expression)) return false;
            var value = expression.Trim();
            foreach (var localName in localNames)
                if (value == localName || value.StartsWith(localName + ".", StringComparison.Ordinal) ||
                    value.StartsWith(localName + "[", StringComparison.Ordinal)) return true;
            return false;
        }

        private static bool IsWrapperExpression(SqxNode node)
        {
            if (node is not SqxExpression expression) return false;
            var value = expression.Expression.Trim();
            return value.EndsWith("=>", StringComparison.Ordinal) || value == "}";
        }

        private static bool IsTemplateFragment(SqxElement element) =>
            string.Equals(element.TagName, "Fragment", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(element.TagName, "template", StringComparison.OrdinalIgnoreCase);

        private static SqxAttribute FindAttr(SqxElement element, string name) =>
            element.Attributes.FirstOrDefault(attribute => string.Equals(attribute.Name, name, StringComparison.OrdinalIgnoreCase));

        private static bool HasObjectBindings(IEnumerable<SqxNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is SqxElement element)
                {
                    if (element.Attributes.Any(attribute =>
                        attribute.Name is "__sqv_bind_object" or "__sqv_on_object" ||
                        attribute.IsDynamicProperty || attribute.IsDynamicEvent))
                        return true;
                    if (HasObjectBindings(element.Children)) return true;
                }
                else if (node is TemplateForDirective forDirective)
                {
                    if (HasObjectBindings(forDirective.Children)) return true;
                }
                else if (node is TemplateIfChainDirective ifDirective)
                {
                    foreach (var branch in ifDirective.Branches)
                        if (HasObjectBindings(branch.Children)) return true;
                }
            }
            return false;
        }

        private static bool IsSimpleMemberExpression(string expression)
        {
            if (string.IsNullOrWhiteSpace(expression)) return false;
            foreach (var part in expression.Split('.'))
            {
                if (part.Length == 0 || !(char.IsLetter(part[0]) || part[0] == '_')) return false;
                for (var i = 1; i < part.Length; i++)
                    if (!(char.IsLetterOrDigit(part[i]) || part[i] == '_')) return false;
            }
            return true;
        }

        private static string NormalizeText(string value)
        {
            if (string.IsNullOrWhiteSpace(value)) return "";
            return value.Trim();
        }

        internal void EmitOptionalFactory(List<SqxNode> nodes, string indent, IReadOnlyList<string> localNames)
        {
            EmitFactoryBody(nodes, indent, localNames);
        }

        private static IReadOnlyList<string> AddLocals(IReadOnlyList<string> locals, params string[] names)
        {
            var result = new List<string>(locals);
            foreach (var name in names)
                if (!string.IsNullOrWhiteSpace(name) && !result.Contains(name, StringComparer.Ordinal)) result.Add(name);
            return result;
        }

        private sealed class SlotGroup
        {
            public SlotGroup(string name, bool nameIsExpression, TemplateSlotScope scope, List<SqxNode> nodes)
            {
                Name = name;
                NameIsExpression = nameIsExpression;
                Scope = scope;
                Nodes = nodes;
            }

            public string Name { get; }
            public bool NameIsExpression { get; }
            public TemplateSlotScope Scope { get; }
            public List<SqxNode> Nodes { get; }
        }

        private static string[] Split(string value, char separator) =>
            value == null ? Array.Empty<string>() : value.Split(separator);

        private static string Escape(string value) =>
            value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");

        private static int StableSourceId(string value)
        {
            unchecked
            {
                var hash = 17;
                foreach (var character in value ?? "") hash = hash * 31 + character;
                return hash;
            }
        }

        private static long StableVersion(string value)
        {
            unchecked
            {
                const ulong offset = 14695981039346656037UL;
                const ulong prime = 1099511628211UL;
                var hash = offset;
                foreach (var character in value ?? string.Empty)
                {
                    hash ^= character;
                    hash *= prime;
                }
                return (long)hash;
            }
        }

        private void EmitSourceMappedLine(string indent, int line, string code)
        {
            if (!string.IsNullOrWhiteSpace(_doc.SourcePath) && line > 0)
                _sb.AppendLine("#line " + line + " \"" + Escape(_doc.SourcePath) + "\"");
            _sb.AppendLine(indent + code);
            if (!string.IsNullOrWhiteSpace(_doc.SourcePath) && line > 0)
                _sb.AppendLine("#line default");
        }

        private string MapTagName(string tag) => _templateCatalog.GetComponent(tag).TypeName;

        private TemplateComponentEventDescriptor FindComponentEvent(string variableName, string eventName)
        {
            if (!_variableTags.TryGetValue(variableName, out var tagName)) return null;
            var normalizedTag = tagName.StartsWith("global::", StringComparison.Ordinal)
                ? tagName.Substring("global::".Length)
                : tagName;
            TemplateComponentEventDescriptor[] events = null;
            var currentName = string.IsNullOrWhiteSpace(_namespace)
                ? normalizedTag
                : _namespace + "." + normalizedTag;
            if (!_eventContracts.TryGetValue(currentName, out events) &&
                !_eventContracts.TryGetValue(normalizedTag, out events))
            {
                foreach (var namespaceName in ExtractNamespaceUsings())
                {
                    if (_eventContracts.TryGetValue(namespaceName + "." + normalizedTag, out events))
                        break;
                }
            }
            if (events == null)
            {
                var suffix = "." + normalizedTag;
                var matches = _eventContracts
                    .Where(pair => pair.Key.EndsWith(suffix, StringComparison.Ordinal))
                    .Select(pair => pair.Value)
                    .ToArray();
                if (matches.Length == 1) events = matches[0];
            }
            if (events == null) return null;

            var alias = NormalizeEventAlias(eventName);
            return events.FirstOrDefault(item =>
                NormalizeEventAlias(item.Name).Equals(alias, StringComparison.OrdinalIgnoreCase));
        }

        private static string NormalizeEventAlias(string name) =>
            new string((name ?? string.Empty)
                .Where(character => character != '-')
                .Select(char.ToLowerInvariant)
                .ToArray());

        private IEnumerable<string> ExtractNamespaceUsings()
        {
            var script = _doc.Syntax?.Script;
            if (script == null) yield break;
            foreach (var directive in script.CSharp.Usings)
            {
                if (directive.Alias != null || directive.StaticKeyword.RawKind != 0) continue;
                var name = directive.Name?.ToString();
                if (!string.IsNullOrWhiteSpace(name)) yield return name;
            }
        }

        private bool IsBuiltInTag(string tag) => _templateCatalog.GetComponent(tag).IsBuiltIn;

        private static bool IsBuiltInSlotHost(string tag) =>
            string.Equals(tag, "titlebar", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(tag, "splitcontainer", StringComparison.OrdinalIgnoreCase);

        private bool RequiresBuildAfterAttach(string tag) =>
            !IsBuiltInTag(tag) || IsBuiltInSlotHost(tag);

        private bool IsTextContentElement(string tag) => _templateCatalog.GetComponent(tag).IsTextContentElement;

        private string MapPropName(string name) => _templateCatalog.MapPropertyName(name);

        private sealed class RefInfo
        {
            public string Name { get; }
            public string TypeName { get; }

            public RefInfo(string name, string typeName)
            {
                Name = name;
                TypeName = typeName;
            }
        }
    }
}
