namespace Square.Extensions.WebView;

/// <summary>Represents a JavaScript-to-.NET binding invocation.</summary>
public sealed class WebViewBindingRequest
{
    private readonly WebView _owner;

    internal WebViewBindingRequest(WebView owner, string id, string name, string argumentsJson)
    {
        _owner = owner;
        Id = id;
        Name = name;
        ArgumentsJson = argumentsJson;
    }

    /// <summary>The request identifier generated by the JavaScript bridge.</summary>
    public string Id { get; }

    /// <summary>The bound function name.</summary>
    public string Name { get; }

    /// <summary>The JSON array containing the JavaScript function arguments.</summary>
    public string ArgumentsJson { get; }

    /// <summary>Completes the JavaScript promise associated with this request.</summary>
    public Task ReturnAsync(int status, string result, CancellationToken cancellationToken = default) =>
        _owner.ReturnAsync(Id, status, result, cancellationToken);
}

/// <summary>Receives a call from a JavaScript binding.</summary>
public delegate ValueTask WebViewBindingHandler(WebViewBindingRequest request);
