<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Square\Square.csproj" />
    <ProjectReference Include="..\..\src\Square.Extensions\Square.Extensions.csproj" />
    <ProjectReference Include="..\..\src\Square.Extensions.Markdown\Square.Extensions.Markdown.csproj" />
    <ProjectReference Include="..\..\samples\Square.Sample\Square.Sample.csproj" />
    <ProjectReference Include="..\..\samples\Square.Sample.Vue\Square.Sample.Vue.csproj" />
    <ProjectReference Include="..\..\tools\Square.FontComparison\Square.FontComparison.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="resource-priority.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="global-base.css" CopyToOutputDirectory="PreserveNewest" />
    <None Update="global-overrides.css" CopyToOutputDirectory="PreserveNewest" />
    <None Update="css-imports\**\*.css" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
